server:
  port: 8080
spring:
  application:
    name: Kerlink2Lo

lo:
  hostname: liveobjects.orange-business.com
  api-key: _api_key_
  keep-alive-interval-seconds: 30
  automatic-reconnect: true
  message-qos: 1
  mqtt-persistence-dir: ${basedir:.}/temp/
  connection-timeout: 30000
  page-size: 20
  synchronization-device-interval: PT10M
  message-decoder: test_csv

kerlink-global:
  login-interval: PT5H

kerlink-list:
  -
    base-url: https://_your_wmc_host_/gms
    login: _kerlink_login_
    password: _kerlink_password
    page-size: 20
    kerlink-account-name: _kerlink_account_name

  -
    base-url: https://_your_wmc_host_/gms
    login: _kerlink_login_
    password: _kerlink_password
    page-size: 20
    kerlink-account-name: _kerlink_account_name

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, beans, counters
  endpoint:
    health:
      show-details: ALWAYS
  health:
    defaults:
      enabled: false